version: '3.7'

services:
  mysqldb:
    image: mysql
    restart: always
    ports: 
      - 3308:3306
    volumes: 
      - mysqldb-data:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: 'REGISTRATORDB'
      MYSQL_USER: registrator_usr
      MYSQL_PASSWORD: '4UHE,3q,w7X3?X+(TA'
      MYSQL_ROOT_PASSWORD: 'P@$$word'

  registrator:
    restart: always
    build:
      context: ./registrator-service
      dockerfile: Dockerfile
    depends_on: 
      - mysqldb
    ports: 
      - 8081:8080
    environment: 
      SPRING_ACTIVE_PROFILE: local
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/REGISTRATORDB?zeroDateTimeBehavior=convertToNull
      SPRING_DATASOURCE_USERNAME: registrator_usr
      SPRING_DATASOURCE_PASSWORD: '4UHE,3q,w7X3?X+(TA'

#  ui:
#    restart: always
#    build:
#      context: ./registrator-ui
#      dockerfile: Dockerfile
#    depends_on: 
#      - mysqldb
#      - registrator
#    ports: 
#      - 4201:4200
      
volumes: 
  mysqldb-data: